# site settings
title: William Ozeas
subtitle: Portfolio
email: williamozeas@gmail.com
description: Programming & Sound
url: "https://williamozeas.github.io" # the base hostname & protocol for your site
author: William Ozeas
phone: (818) 421-4380

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/williamozeas
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/william-ozeas/
  Twitter: https://twitter.com/WillOzeas
  Facebook:
  Soundcloud: https://soundcloud.com/willowpet

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
